cute_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint1
     - joint2
     - joint3
     - joint4
     - joint5
     - joint6
     - joint7
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.2
  stop_trajectory_duration: 0
  state_publish_rate:  25
  action_monitor_rate: 10
